### ISSUE TITLE
bug when call ranking with options:date

### ISSUE THREAD

**Issue by yanagiragi** [akameco/pixiv#8]
pix.ranking('all',{ date : processedDate }).then( res => {
    // do something with response[0].works
});

For some dates, e.g. processDate = '2016-08-01' or '2016-07-31' , it returns a json format data with response[0].work.length equals 0, however if I choose to pass nothing aka. using default option, it returns data correctly, looking forward to fix this bug.

BTW, though it is not as completed as pixivpy, I'm amazed by your work so far and appreciated for there's someone providing such useful pixiv api for node.js. Nice work!

**Comment by akameco** [comment]
Thank.

This is not bug.

The latest rankings of pixiv is one day before the data is aggregated.

For example, today (8/4) has been reflected in those of the 8/3.
You can see this if you look at the rankings page of pixiv.

[[pixiv] Overall Daily Rankings 2016/8/4](http://www.pixiv.net/ranking.php)

<img width="836" alt="_1___pixiv__ _2016 8 3 _ _shell" src="https://cloud.githubusercontent.com/assets/4002137/17392182/93f150dc-5a56-11e6-9744-6412ec9977bc.png">

Sorry for my poor English.

**Comment by yanagiragi** [comment]
I See. Thanks a lot !
